[workspace]
resolver = "3"
members = [
    "apps/dryrun",
    "crates/contract-standards",
    "crates/conflux-provider",
    "crates/evm-simulation",
    "crates/evm-rpc",
    "crates/conflux-simulation",
    "crates/conflux-rpc",
    "crates/simulation-tasks",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
contract-standards = { path = "crates/contract-standards" }
conflux-provider = { path = "crates/conflux-provider" }
evm-simulation = { path = "crates/evm-simulation" }
evm-rpc = { path = "crates/evm-rpc" }
conflux-simulation = { path = "crates/conflux-simulation" }
conflux-rpc = { path = "crates/conflux-rpc" }
simulation-tasks = { path = "crates/simulation-tasks" }

jsonrpsee = "0.26"
thiserror = "2"

tokio = "1"
tokio-util = "0.7"

alloy = "1"
alloy-json-rpc = "1"
alloy-serde = "1"
alloy-rpc-client = { version = "1", default-features = false }
alloy-transport = { version = "1", default-features = false }
alloy-chains = "0.2"
alloy-eips = "1"
alloy-hardforks = "0.4"
alloy-primitives = "1"
alloy-sol-types = "1"
revm = "36"

cfx-types = { git = "https://github.com/iosh/conflux-rust.git", branch = "dry" }
cfx-bytes = { git = "https://github.com/iosh/conflux-rust.git", branch = "dry" }
cfx-addr = { git = "https://github.com/iosh/conflux-rust.git", branch = "dry" }
cfx-rpc-cfx-types = { git = "https://github.com/iosh/conflux-rust.git", branch = "dry" }
cfx-rpc-primitives = { git = "https://github.com/iosh/conflux-rust.git", branch = "dry" }
cfx-rpc-eth-types = { git = "https://github.com/iosh/conflux-rust.git", branch = "dry" }
primitives = { git = "https://github.com/iosh/conflux-rust.git", branch = "dry" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

tracing = "0.1"
tracing-subscriber = "0.3"

config = "0.15"

metrics = "0.24"
metrics-exporter-prometheus = "0.18"
axum = "0.8"
