[package]
name = "conflux-simulation"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy = { workspace = true }
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
conflux-provider = { workspace = true }
contract-standards = { workspace = true }
cfx-bytes = { workspace = true }
cfx-types = { workspace = true }
primitives = { workspace = true }
cfx-storage = { git = "https://github.com/iosh/conflux-rust.git", branch = "dry" }
cfx-statedb = { git = "https://github.com/iosh/conflux-rust.git", branch = "dry" }
cfx-internal-common = { git = "https://github.com/iosh/conflux-rust.git", branch = "dry" }
cfx-parameters = { git = "https://github.com/iosh/conflux-rust.git", branch = "dry" }
cfx-addr = { workspace = true }

cfx-executor = { git = "https://github.com/iosh/conflux-rust.git", branch = "dry" }
cfx-vm-types = { git = "https://github.com/iosh/conflux-rust.git", branch = "dry" }

cfx-rpc-cfx-types = { workspace = true }
cfx-rpc-primitives = { workspace = true }

cfx-rpc-eth-types = { workspace = true }
keccak-hash = "0.5"
rlp = "0.4"
serde = { workspace = true }
serde_json = { workspace = true }
simulation-changes = { workspace = true }
simulation-execution = { workspace = true }
simulation-transaction = { workspace = true }
thiserror = { workspace = true }
typemap = { package = "typemap-ors", version = "1.0" }
tokio = { workspace = true, features = ["rt-multi-thread", "sync"] }
tracing = { workspace = true }
