[package]
name = "conflux-simulation"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
simulation-core = { workspace = true }
conflux-provider = { workspace = true }
alloy = { workspace = true, features = ["consensus", "eips", "providers", "rpc-types"] }
alloy-primitives = { workspace = true }
alloy-serde = { workspace = true }
alloy-sol-types = { workspace = true }
cfx-types = { workspace = true }
cfx-rpc-eth-types = { workspace = true }
primitives = { workspace = true }
cfx-executor = { workspace = true }
cfx-vm-types = { workspace = true }
cfx-storage = { workspace = true }
cfx-statedb = { workspace = true }
cfx-internal-common = { workspace = true }
cfx-parameters = { workspace = true }
keccak-hash = "0.12"
rlp = "0.6"
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "sync"] }
typemap = { package = "typemap-ors", version = "1.0" }
