[package]
name = "evm-rpc"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
simulation-core = { workspace = true, features = ["serde"] }
jsonrpsee = { workspace = true, features = ["server", "macros"] }
serde = { workspace = true, features = ["rc"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
alloy-primitives = { workspace = true }
alloy-serde = { workspace = true }
contract-standards = { workspace = true }
evm-simulation = { workspace = true, features = ["serde"] }
simulation-tasks = { workspace = true }
