[package]
name = "dryrun"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
simulation-core = { workspace = true }
evm-simulation = { workspace = true }
alloy = { workspace = true, features = ["provider-http"] }
axum = { workspace = true }
config = { workspace = true }
jsonrpsee = { workspace = true, features = ["server"] }
metrics-exporter-prometheus = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
