[package]
name = "dryrun"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
conflux-simulation = { workspace = true }
conflux-rpc = { workspace = true }
conflux-service = { workspace = true }
evm-simulation = { workspace = true }
evm-rpc = { workspace = true }
evm-service = { workspace = true }
simulation-tasks = { workspace = true }
jsonrpsee = { workspace = true, features = ["server"] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
metrics-exporter-prometheus = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
config = { workspace = true }
alloy = { workspace = true }
alloy-rpc-client = { workspace = true, features = ["reqwest"] }
conflux-provider = { workspace = true }
