[package]
name = "simulation-core"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy-eips = { workspace = true }
alloy-primitives = { workspace = true, features = ["serde"] }
alloy-serde = { workspace = true }
alloy-sol-types = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
alloy-consensus = { workspace = true }
